name: neuralvolumes
channels:
  - pytorch
  - nvidia/label/cuda-11.6.2
  - conda-forge
  - defaults
dependencies:
  - torchaudio
  - pytorch
  - torchvision
  - cudatoolkit=11.6
  - matplotlib
  - opencv
  - scipy
  - cuda
  - pyvista
  - tqdm
  - pymeshfix
  - wandb
  - cudnn
  - pylint
  - icecream
