name: neuralvolumes
channels:
  - conda-forge
  - defaults
dependencies:
  - torchaudio
  - pytorch
  - torchvision
  - cudatoolkit=11.6
  - matplotlib
  - opencv
  - scipy
  - cuda
  - pyvista
  - tqdm
  - pymeshfix
  - wandb
