name: neuralvolumes
channels:
  - pytorch
  - nvidia/label/cuda-11.6.2
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - appdirs=1.4.4
  - blas=2.116
  - blas-devel=3.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.5
  - contourpy=1.0.5
  - cryptography=37.0.4
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.6.124
  - cuda-nsight-compute=11.6.2
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.6.124
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.6.124
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.6.124
  - cuda-runtime=11.6.2
  - cuda-sanitizer-api=11.6.124
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - cudatoolkit=11.6.0
  - curl=7.85.0
  - cycler=0.11.0
  - docker-pycreds=0.4.0
  - double-conversion=3.2.0
  - eigen=3.4.0
  - expat=2.4.9
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.3
  - freeglut=3.2.2
  - freetype=2.12.1
  - gettext=0.19.8.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imageio=2.22.0
  - intel-openmp=2022.1.0
  - jasper=2.0.33
  - jpeg=9e
  - jsoncpp=1.9.5
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.2.9.124
  - libcurand-dev=10.2.9.124
  - libcurl=7.85.0
  - libcusolver=11.3.4.124
  - libcusolver-dev=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.14
  - libffi=3.4.2
  - libglib=2.72.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libogg=1.3.4
  - libopencv=4.6.0
  - libpng=1.6.38
  - libprotobuf=3.21.7
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.4.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzip=1.9.2
  - libzlib=1.2.12
  - loguru=0.6.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.6.0
  - matplotlib-base=3.6.0
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nsight-compute=2022.1.1.2
  - numpy=1.23.3
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pathtools=0.1.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - proj=9.0.1
  - promise=2.3
  - protobuf=4.21.7
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pugixml=1.11.4
  - py-opencv=4.6.0
  - pycparser=2.21
  - pymeshfix=0.16.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyvista=0.36.1
  - pyyaml=6.0
  - qt-main=5.15.6
  - requests=2.28.1
  - scipy=1.9.1
  - scooby=0.6.0
  - sentry-sdk=1.9.10
  - setproctitle=1.3.2
  - setuptools=65.3.0
  - shortuuid=1.0.9
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.39.3
  - svt-av1=1.2.1
  - tbb=2021.6.0
  - tbb-devel=2021.6.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - utfcpp=3.2.1
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - vtk=9.1.0
  - wandb=0.13.4
  - wheel=0.37.1
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
